### ISSUE TITLE
\dt schema.*

### ISSUE THREAD

**Issue by fzerorubigd** [amjith/pgcli#82] opened 2015-01-08 12:25 UTC
`\dt *.*` and `\dt schema.*` has no effect at all. its always show public schema tables.

**Comment by fzerorubigd** [comment] 2015-01-08 12:29
I don't know if compatibility with psql is a goal or not? since I found the `\dn` is not implemented also.

**Comment by amjith** [comment] 2015-01-08 19:37
Yes `schema` support is still pending #22. 

Compatibility with psql is indeed a goal. But it takes time to catch up with years of work. :)

`\dn` is currently pending in a PR #62. I'll merge it in once I get a chance to review it.

**Comment by fzerorubigd** [comment] 2015-01-08 21:23
Thank you for your fast response!
So this is duplicate of them, I close this one.

**Comment by amjith** [comment] 2015-01-27 04:35
Schema support is added to master. Sql statements with schema names now have auto-completion (thanks @darikg). 

But \dt schema is still broken. So I'm reopening the issue. 

\dn is available in master.

**Comment by darikg** [comment] 2015-01-31 14:07
Looking into this a bit, the problem is that the \dt special command currently ignores the following argument, so no filtering of any sort is done, it just shows all public tables no matter what.

psql seems to work like the following pseudo-python:
```
# Accept an argument of the form [schema_filter.][table_filter]
if schema_filter:
    if schema_filter == '*':
        pass
    else:
        sql += " AND n.nspname ~ '^(schema_filter)$' "
else:
    sql += " AND pg_catalog.pg_table_is_visible(c.oid) "

if table_filter:
    if table_filter == '*':
        pass
    else:
        sql += " AND c.relname ~ '^(table_filter)$' "
```

So the biggest impediment to fixing this issue is figuring out how to parse the argument into a schema filter and table filter, converting wildcards '*' and '?' into regex syntax, and respecting double quotes

**Comment by amjith** [comment] 2015-01-31 21:03
There's already functions in pgspecial.py to do the wildcard conversion and double quotes escaping. 

https://github.com/amjith/pgcli/blob/master/pgcli/packages/pgspecial.py#L706

**Comment by amjith** [comment] 2015-02-05 07:10
This is now fixed in master. Thanks to @darikg. 

Can you try it out? You can install from the git repo directly:

```
pip install -U -e git+https://github.com/amjith/pgcli.git#egg=pgcli
```

**Comment by fzerorubigd** [comment] 2015-02-05 16:43
I get this error on debian, and archlinux right after launch pgcli : 
```
Traceback (most recent call last):
  File "/usr/bin/pgcli", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pgcli==0.14.0
```

**Comment by amjith** [comment] 2015-02-05 17:17
You probably have an older version of pgcli installed from the git repo. 

Did you try the `pip install -U -e git+https://github.com/amjith/pgcli.git#egg=pgcli`? 

If you have then can you do `pip uninstall pgcli` and then try `pip install -U -e git+https://github.com/amjith/pgcli.git#egg=pgcli`?

**Comment by fzerorubigd** [comment] 2015-02-05 17:40
```
pip uninstall pgcli
Uninstalling pgcli:
  /usr/bin/pgcli
  /usr/lib/python2.7/site-packages/pgcli.egg-link
Proceed (y/n)? y
  Successfully uninstalled pgcli
```
```
pip install -U -e git+https://github.com/amjith/pgcli.git#egg=pgcli                                        
Obtaining pgcli from git+https://github.com/amjith/pgcli.git#egg=pgcli
  Updating ./src/pgcli clone
  Running setup.py egg_info for package pgcli
    
Requirement already up-to-date: click>=3.2 in /usr/lib/python2.7/site-packages (from pgcli)
Requirement already up-to-date: Pygments>=2.0 in /usr/lib/python2.7/site-packages (from pgcli)
Requirement already up-to-date: jedi==0.8.1 in /usr/lib/python2.7/site-packages (from pgcli)
Requirement already up-to-date: prompt-toolkit==0.26 in /usr/lib/python2.7/site-packages (from pgcli)
Requirement already up-to-date: psycopg2>=2.5.4 in /usr/lib/python2.7/site-packages (from pgcli)
Requirement already up-to-date: sqlparse>=0.1.14 in /usr/lib/python2.7/site-packages (from pgcli)
Requirement already up-to-date: docopt in /usr/lib/python2.7/site-packages (from prompt-toolkit==0.26->pgcli)
Requirement already up-to-date: six>=1.8.0 in /usr/lib/python2.7/site-packages (from prompt-toolkit==0.26->pgcli)
Requirement already up-to-date: wcwidth in /usr/lib/python2.7/site-packages (from prompt-toolkit==0.26->pgcli)
Installing collected packages: pgcli
  Running setup.py develop for pgcli
    
    Creating /usr/lib/python2.7/site-packages/pgcli.egg-link (link to .)
    Adding pgcli 0.14.0 to easy-install.pth file
    Installing pgcli script to /usr/bin
    
    Installed /root/src/pgcli
Successfully installed pgcli
Cleaning up...
```

```
$ pgcli 
Traceback (most recent call last):
  File "/usr/bin/pgcli", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pgcli==0.14.0
```

**Comment by amjith** [comment] 2015-02-05 17:57
That's odd. Can you try uninstalling twice and try again?

I've seen this happen occasionally. Try `pip uninstall pgcli` and then
issue that command again `pip uninstall pgcli` then try installing?

**Comment by fzerorubigd** [comment] 2015-02-05 18:45
I do it 3 time, first just ask my to remove, next it print a bunch of file for delete and third time : 
``` 
pip uninstall pgcli
Cannot uninstall requirement pgcli, not installed
```

And after installing, the problem still there. 
```
Traceback (most recent call last):
  File "/usr/bin/pgcli", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 612, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 918, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pgcli==0.14.0

```
Do I miss something? :/

**Comment by amjith** [comment] 2015-02-05 18:46
Can you jump on https://gitter.im/amjith/pgcli?

**Comment by fzerorubigd** [comment] 2015-02-05 19:39
@amjith thanks for your time and help. I can confirm that the the `\dt` is working as expected. 
and thank you @darikg

**Closed** 2015-02-05 19:39 UTC
