### ISSUE TITLE
Add support for .pgpass

### ISSUE THREAD

**Issue by allan-simon** [amjith/pgcli#53] opened 2015-01-07 06:56 UTC
it seems pgcli is not making use of this file 
https://wiki.postgresql.org/wiki/Pgpass

**Comment by amjith** [comment] 2015-01-07 07:36
Yeah, I didn't know about .pgpass. I'll add support for it. 

Thanks for reporting it.

**Comment by darikg** [comment] 2015-01-07 16:09
pgpass already works on my computer without having to do anything. I think it's handled by [psycopg2](http://psycopg.lighthouseapp.com/projects/62710/tickets/54-feature-request-add-support-for-a-pgpass-connect-parameter). I have psycopg2 2.5.4 on a windows machine.

**Comment by felixhummel** [comment] 2015-01-07 22:15
Does not work for me on Ubuntu 12.04 with

    $ python -c 'import psycopg2; print psycopg2.__version__'
    2.5.4 (dt dec pq3 ext)
    $ python -c 'import pgcli; print pgcli.__version__'
    0.10.2

**Comment by amjith** [comment] 2015-01-08 07:10
I suspect that this might be the doing of `libpq` and not `psycopg2`. I have to read through the docs to further under how .pgpass is used and where it's accessed. 

Can you both (@felixhummel and @darikg) tell me the versions of postgres and postgres-dev packages?

**Comment by darikg** [comment] 2015-01-08 13:07
postgres 9.4 on one machine and 9.2 on another. I'm not sure how to check libpq version in windows.

**Comment by kanet77** [comment] 2015-01-08 18:54
To add another data point:

.pgpass works for me with the following command:
```pgcli -h localhost -U <user_name> <database_name>```

I confirmed by renaming .pgpass and observing pgcli fail with the following error message:
```fe_sendauth: no password supplied```

Environment:
- OSX 10.10
- PostgreSQL 9.4.0 (installed w/ brew)
- pgcli (0.10.3) (also worked w/ 0.10.1)
- Python 2.7.9
- pip 1.5.6

**Comment by felixhummel** [comment] 2015-01-08 22:36
@amjith For me it's postgres 9.3. Same goes for the dev package. Got it via postgresql.org's debian repo.
This works, btw:

    psql DBNAME USERNAME

**Comment by manuelRiel** [comment] 2015-04-03 02:00
Confirming this already works.

`pgcli -h HOST -U USER DB`

**Comment by amjith** [comment] 2015-04-03 05:05
This is a feature of libpq as described in the original wiki page. https://wiki.postgresql.org/wiki/Pgpass

libpq is the library used by psycopg2 and pgcli. So pgpass should already work as expected. 

I've tested this on OS X and the overwhelming confirmation from multiple users confirm that it does work as expected. 

So I'm closing this ticket.

**Closed by amjith** 2015-04-03 05:05 UTC
Labels: enhancement

**Comment by j4sper** [comment] 2015-10-13 22:46
Whether pgcli works or not depends on the order of arguments.  

`pgcli -h HOST -U USER DBNAME` works fine, but `pgcli -U USER -h HOST DBNAME` does not.  

Both versions would work with the `psql` command.

**Comment by amjith** [comment] 2015-10-14 11:22
@j4sper I tried it on OS X and I still can't reproduce it. 

Can you tell me what's the version of pgcli you're using? 

Also what is the version of postgres are you connecting to?

**Comment by j4sper** [comment] 2015-10-14 15:31
@amjith Maybe I had an error in my .pgpass.  I couldn't reproduce it today either.
